from proyecto.analisis.procesado.ProcesadoDeImagen import ProcesadoDeImagen
from proyecto.analisis.procesado.ProcesadoDeLineas import ProcesadoDeLineas
from Test.codigo.procesado.TestProcesadoDeImagen import TestProcesadoDeImagen
from Test.codigo.procesado.TestProcesadoDeLineas import TestProcesadoDeLineas
