from proyecto.codigo.procesado.ProcesadoDeImagen import ProcesadoDeImagen
from proyecto.codigo.procesado.ProcesadoDeLineas import ProcesadoDeLineas
from Test.codigo.procesado.TestProcesadoDeImagen import TestProcesadoDeImagen
from Test.codigo.procesado.TestProcesadoDeLineas import TestProcesadoDeLineas
from Test.codigo.procesado.MatrizConfusion import MatrizConfusion