from proyecto.analisis.procesado.ProcesadoDeLineas import ProcesadoDeLineas
from proyecto.analisis.procesado.ProcesadoDeImagen import ProcesadoDeImagen
from proyecto.analisis.procesado.ProcesadoAutomatico import ProcesadoAutomatico

from proyecto.analisis.informes.Informe import Informe
from proyecto.analisis.informes.DatosToCsv import DatosToCsv
from proyecto.analisis.informes.InGuardarDatos import InGuardarDatos
from proyecto.analisis.informes.ConfiguracionToXML import ConfiguracionToXML

from proyecto.analisis.estadisticas.Estadistica import Estadistica

from proyecto.analisis.diccionario.Diccionario import Diccionario
from proyecto.analisis.diccionario.DiccionarioING import DiccionarioING

from proyecto.analisis.FachadaBotonesAndLayaout import FachadaBotonesAndLayaout
from proyecto.analisis.FachadaEntradaSalida import FachadaEntradaSalida
from proyecto.analisis.MediadorVentana import MediadorVentana
from proyecto.analisis.MediadorPestannas import MediadorPestannas