from proyecto.codigo.procesado.ProcesadoDeLineas import ProcesadoDeLineas
from proyecto.codigo.procesado.ProcesadoDeImagen import ProcesadoDeImagen
from proyecto.codigo.procesado.ProcesadoAutomatico import ProcesadoAutomatico