from proyecto.analisis.procesado.ProcesadoDeLineas import ProcesadoDeLineas
from proyecto.analisis.procesado.ProcesadoDeImagen import ProcesadoDeImagen
from proyecto.analisis.procesado.ProcesadoAutomatico import ProcesadoAutomatico